package com.kirson.ecommerceconcept.ui.theme

internal val DarkColorPalette = AppColors(
    primaryColor = Red1,
    secondaryColor = Blue1,
    backgroundPrimary = Dark1,
    backgroundSecondary = Blue1,
    contendPrimary = Dark3,
    contendSecondary = Dark4,
    contendTertiary = Dark5,
    contendAccentPrimary = Blue1,
    contendAccentSecondary = Pink1,
    contendAccentTertiary = Light1,
    textPrimary = Light1,
    textSecondary = Dark6,
    textTertiary = Dark5,
    indicatorContendError = Red1,
    indicatorContendDone = Green1,
    indicatorContendSuccess = Blue1,
    primaryButton = Blue1,
    bottomMenuBackground = Blue1,
    scrimer = Dark7.copy(alpha = 0.25f),
    calendarPeriod = Blue1.copy(alpha = 0.2f),
    buttonSecondary = Light1,
    black = Dark7,
    textButton = Light1,
    isDark = true,
    shadowColor = Dark1,
    tornado1 = listOf(Shadow4, Ocean3)
)