package com.kirson.ecommerceconcept.ui.theme

internal val LightColorPalette = AppColors(
    primaryColor = Red1,
    secondaryColor = Blue1,
    backgroundPrimary = Light1,
    backgroundSecondary = Blue1,
    contendPrimary = Light2,
    contendSecondary = Light2,
    contendTertiary = Dark6,
    contendAccentPrimary = Blue2,
    contendAccentSecondary = Light1,
    contendAccentTertiary = Dark8,
    textPrimary = Dark8,
    textSecondary = Dark9,
    textTertiary = Dark10,
    indicatorContendError = Red2,
    indicatorContendDone = Green2,
    indicatorContendSuccess = Blue2,
    primaryButton = Blue2,
    bottomMenuBackground = Blue1,
    scrimer = Dark11.copy(alpha = 0.2f),
    calendarPeriod = Blue2.copy(alpha = 0.2f),
    buttonSecondary = Blue2,
    black = Dark7,
    textButton = Light1,
    isDark = true,
    shadowColor = Light1,
    tornado1 = listOf(Shadow4, Ocean3)
)